function [  ] = inpHeader( fid, meta )
%INPHEADER - write a header for the .imp file
%
%   Inputs:
%       fid - file id (as set by fopen)
%       meta - structure
%           meta.job - job name
%           meta.model - model name
%           meta.gen - toolbox name
%

if ~isfield(meta,'job')
    meta.job = 'Job-default-feOCE';
end
if ~isfield(meta,'model')
    meta.model = 'Model-1';
end
if ~isfield(meta,'gen')
    meta.gen = 'COP-toolbox';
end

fprintf(fid,'*Heading\n');
fprintf(fid,'** Job name: %s Model name: %s\n',meta.job, meta.model);
fprintf(fid,'** Generated by: %s\n',meta.gen);
fprintf(fid,'*Preprint, echo=NO, model=NO, history=NO, contact=NO\n');

end